version: '3.1'

services:

  app:
    build: .
    restart: always
    ports: 
      - 80:4567
    depends_on: 
      - db

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: postgres
    ports:
      - 5432:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes: 
  postgres-data:
    driver: local